Pres = {}
Pres.NameFA = {}
Pres.NameFA[1]		= "ÅÌòÊ"
Pres.NameFA[2]		= "‰«‰Ê"
Pres.NameFA[3]		= "„Ìò—Ê"
Pres.NameFA[4]		= "„Ì·Ì"
Pres.NameFA[5]		= "”«‰ Ì"
Pres.NameFA[6]		= "œ”Ì"
Pres.NameFA[7]		= "œò«"
Pres.NameFA[8]		= "Âò Ê"
Pres.NameFA[9]		= "òÌ·Ê"
Pres.NameFA[10]		= "„ê«"
Pres.NameFA[11]		= "êÌê«"
Pres.NameFA[12]		= " —«"

Pres.Symbol = {}
Pres.Symbol[1]		= "p"
Pres.Symbol[2]		= "n"
Pres.Symbol[3]		= "Mu"
Pres.Symbol[4]		= "m"
Pres.Symbol[5]		= "c"
Pres.Symbol[6]		= "d"
Pres.Symbol[7]		= "da"
Pres.Symbol[8]		= "h"
Pres.Symbol[9]		= "k"
Pres.Symbol[10]		= "M"
Pres.Symbol[11]		= "G"
Pres.Symbol[12]		= "T"

Pres.Value = {}
Pres.Value[1]	= 10^(-12);
Pres.Value[2]	= 10^(-9);
Pres.Value[3]	= 10^(-6);
Pres.Value[4]	= 10^(-3);
Pres.Value[5]	= 10^(-2);
Pres.Value[6]	= 10^(-1);
Pres.Value[7]	= 10
Pres.Value[8]	= 10^2
Pres.Value[9]	= 10^3
Pres.Value[10]	= 10^6
Pres.Value[11]	= 10^9
Pres.Value[12]	= 10^12